name: Run RSpec tests on Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rspec_job:
    name: Run RSpec tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Set up Docker
        run: bundle exec rake redis:setup

      - name: Build Tailwind CSS
        run: rails tailwindcss:build

      - name: Run RSpec tests
        run: bundle exec rspec
  deplo_job:
    needs: rspec_job  # This job runs only if the 'rspec_job' job succeeds
    if: github.ref == 'refs/heads/main'  # Ensures deployment runs only for pushes to main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_APP_NAME }} --api-key=${{ secrets.HEROKU_API_KEY }}
